### ISSUE TITLE
TypeError: Cannot read property 'size' of undefined

### ISSUE THREAD

**Issue by shootyou** [NarrativeScience/log.io#161]
/usr/local/lib/node_modules/log.io/lib/harvester.js:90
            _this._readNewLogs(path, stat.size, currSize);
                                         ^
TypeError: Cannot read property 'size' of undefined
    at /usr/local/lib/node_modules/log.io/lib/harvester.js:90:42
    at FSReqWrap.oncomplete (fs.js:95:15)
/usr/local/lib/node_modules/log.io/lib/harvester.js:90
            _this._readNewLogs(path, stat.size, currSize);
                                         ^
TypeError: Cannot read property 'size' of undefined
    at /usr/local/lib/node_modules/log.io/lib/harvester.js:90:42
    at FSReqWrap.oncomplete (fs.js:95:15)

When this happens,the 'harvester' goes down.

**Comment by shootyou** [comment]
I guess removing log files will cause this exception.
