### ISSUE TITLE
log.io on RaspberryPi B+

### ISSUE THREAD

**Issue by akrv** [NarrativeScience/log.io#164]
Hi,
I tried to install with the instructions and fails on the RPi B+ with this on the logs
cake ensure:configuration

following is the error: i tried to run as root also replacing ubuntu with pi

```
> cake ensure:configuration

wCreating ~/.log.io/ for configuration files.
If this fails, run npm using a specific user: npm install -g log.io --user 'ubuntu'
fs.js:747
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: EACCES, permission denied '/root/.log.io/'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at Object.action (/usr/local/lib/node_modules/log.io/Cakefile:79:10)
    at helpers.extend.invoke (/usr/local/lib/node_modules/log.io/node_modules/coffee-script/lib/coffee-script/cake.js:44:26)
    at Object.exports.run (/usr/local/lib/node_modules/log.io/node_modules/coffee-script/lib/coffee-script/cake.js:69:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/log.io/node_modules/coffee-script/bin/cake:7:38)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by ColtraneNadler** [comment]
the user you are trying to install it with- does not have permission to edit certain directories that need to be edited in order to install this. run as root- or edit your permissions. :)

**Comment by msmathers** [comment]
v0.4.3 is a full rewrite that uses node.js 12 and no longer requires root/sudo, so this issue should be resolved.
