### ISSUE TITLE
fail install on windows

### ISSUE THREAD

**Issue by zhaoyou** [NarrativeScience/log.io#168]
``` bash
$ npm install -g log.io --user "windows"

> contextify@0.1.14 install c:\Program Files (x86)\nodejs\node_modules\log.io\node_modules\jquery\node_modules\contextify
> node-gyp rebuild

-
c:\Program Files (x86)\nodejs\node_modules\log.io\node_modules\jquery\node_modules\contextify>if not defined npm_config_node_gyp (node "c:\Users\Admin
istrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node c
:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\bin\node-gyp.js rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Wi
ndows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [c:\Program Files (x86)\nodejs\node_modules\lo
g.io\node_modules\jquery\node_modules\contextify\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Program Files (x86)\nodejs\node_modules\log.io\node_modules\jquery\node_modules\contextify
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
\


> ws@0.4.32 install c:\Program Files (x86)\nodejs\node_modules\log.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


c:\Program Files (x86)\nodejs\node_modules\log.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "c:\Users\Adm
inistrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
 c:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\bin\node-gyp.js rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Wi
ndows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [c:\Program Files (x86)\nodejs\node_modules\lo
g.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Wi
ndows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [c:\Program Files (x86)\nodejs\node_modules\lo
g.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]

> ws@0.4.32 install c:\Program Files (x86)\nodejs\node_modules\log.io\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


c:\Program Files (x86)\nodejs\node_modules\log.io\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_
gyp (node "c:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js
" rebuild )  else (node c:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\bin\node-gyp.js rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Wi
ndows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [c:\Program Files (x86)\nodejs\node_modules\lo
g.io\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Wi
ndows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [c:\Program Files (x86)\nodejs\node_modules\lo
g.io\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "c:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users
\\Administrator\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=C:\\Users\\Administrator\\.cnpm" "--registry=https://registry.npm.t
aobao.org" "--node-gyp=c:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "-g" "
log.io" "--user" "windows"
npm ERR! node v0.12.5
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log
```

**Comment by jwusch** [comment]
So you  need to install Microsoft Visual Studio 2015 on windows, as well as then creating a C++ project inside of Visual Studio so that it downloads additional header files so it can complie.  Very weird dependencies but they exist..

**Comment by theotherp** [comment]
It would be nice to mention that somewhere on your page and not pretend installation is as easy as calling NPM.

**Comment by TrumbleTBeran** [comment]
Here is my procedure I created to instlal log.io on windows 

download and install nodejs 6.10 (NOTE 7.10 doesn't work)

open node.js console as administrator

npm install -g npm-windows-upgrade
npm-windows-upgrade
npm install --global --production windows-build-tools
npm install --global node-gyp
npm install -g log.io

#To Start server run in powershell window
log.io-server

#To Start harvester run in powershell windows
log.io-harvester

**Comment by pedoc** [comment]
@ghost hi,not working for me,this output

```
C:\Users\pedoc\AppData\Local\node-gyp\Cache\10.15.3\include\node\v8.h(10046): message : 参见“v8::Value::ToObject”的声明 [D:\
Users\
pedoc\AppData\Roaming\npm\node_modules\log.io\node_modules\contextify\build\contextify.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Users\pedoc\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Users\\pedoc\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Users\pedoc\AppData\Roaming\npm\node_modules\log.io\node_modules\contextify
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\pedoc\AppData\Roaming\npm\_logs\2019-10-31T04_36_39_715Z-debug.log
```

[2019-10-31T04_36_39_715Z-debug.log](https://github.com/NarrativeScience/Log.io/files/3792189/2019-10-31T04_36_39_715Z-debug.log)

**Comment by msmathers** [comment]
v0.4.3 is a full rewrite that uses node.js 12, so this issue should be resolved.
