### ISSUE TITLE
Build fails on OSX

### ISSUE THREAD

**Issue by deepal** [NarrativeScience/log.io#169]
Installation fails on Mac OSx with following error. Tried installing with `-g` as well as locally. Both were failed throwing the same error.

```
.
.
.
.
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
In file included from ../src/contextify.cc:1:
In file included from /Users/deepalj/.node-gyp/4.0.0/include/node/node.h:42:
/Users/deepalj/.node-gyp/4.0.0/include/node/v8.h:7367:3: error: assigning to 'v8::Array *volatile' from incompatible type 'v8::Value *'
  TYPE_CHECK(T, S);
  ^~~~~~~~~~~~~~~~
/Users/deepalj/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/contextify.cc:236:13: note: in instantiation of function template specialization 'v8::ReturnValue<v8::Array>::Set<v8::Value>' requested here
            NanReturnValue(blank);
            ^
../../nan/nan.h:401:61: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return args.GetReturnValue().Set(_NanEnsureLocal(value))
                                                            ^
14 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/deepalj/Leapset/projects/logio/node_modules/contextify
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:contextify contextify@0.1.14 install: `node-gyp rebuild`
npm WARN install:contextify Exit status 1

> ws@0.4.32 install /Users/deepalj/Leapset/projects/logio/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
logio@1.0.0 /Users/deepalj/Leapset/projects/logio
├── backbone@0.9.10  extraneous
├── coffee-script@1.4.0  extraneous
├── express@3.0.6  extraneous
├── jquery-browserify@1.8.1  extraneous
├── jsdom@0.2.19  extraneous
├── location@0.0.1  extraneous
├── navigator@1.0.1  extraneous
├── socket.io@0.9.17  extraneous
├── socket.io-client@0.9.17  extraneous
└── winston@0.6.2  extraneous

npm WARN EPACKAGEJSON logio@1.0.0 No description
npm WARN EPACKAGEJSON logio@1.0.0 No repository field.
```

**Comment by jxlwqq** [comment]
same problem

**Comment by deltaworld** [comment]
I also have the same problem

**Comment by rkim-work** [comment]
same problem

**Comment by odegraciajr** [comment]
same here

**Comment by f497196689** [comment]
same

**Comment by msmathers** [comment]
v0.4.3 is a full rewrite that uses node.js v12, so this issue should be resolved.
