### ISSUE TITLE
Error while installing on Debian 8

### ISSUE THREAD

**Issue by Jonn3y** [NarrativeScience/log.io#181]
Heyho,

i compiled nodejs 6.3.1 and installed the last npm (v3.10.5)
then i created a new user: logio
then i tried `/usr/local/bin/npm install -g log.io --user "logio"` as root

``` bash
╭─root@microserver: [~]: Mo Jul 25 > 15:23:46 :
╰─ >>> #  /usr/local/bin/npm install -g log.io --user "logio"
npm WARN deprecated jquery@1.8.3: Versions of the jquery npm package older than 1.9.0 are patched versions that don't work in web browsers. Please upgrade to >=1.11.0.
/usr/local/bin/log.io-server -> /usr/local/lib/node_modules/log.io/bin/log.io-server
/usr/local/bin/log.io-harvester -> /usr/local/lib/node_modules/log.io/bin/log.io-harvester

> contextify@0.1.15 install /usr/local/lib/node_modules/log.io/node_modules/contextify
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.3.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/log.io/node_modules/contextify/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/log.io/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /usr/local/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.3.1/include/node/v8.h:3243): Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
../src/contextify.cc:151:72: warning: ‘void v8::ObjectTemplate::SetAccessCheckCallbacks(v8::NamedSecurityCallback, v8::IndexedSecurityCallback, v8::Local<v8::Value>)’ is deprecated (declared at /usr/local/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.3.1/include/node/v8.h:4767): Use SetAccessCheckCallback instead [-Wdeprecated-declarations]
                                        GlobalPropertyIndexedAccessCheck);
                                                                        ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated (declared at /usr/local/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.3.1/include/node/v8.h:2902): Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated (declared at /usr/local/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.3.1/include/node/v8.h:2902): Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated (declared at /usr/local/lib/node_modules/log.io/node_modules/contextify/.node-gyp/6.3.1/include/node/v8.h:2902): Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
  SOLINK_MODULE(target) Release/obj.target/contextify.node
  COPY Release/contextify.node
make: Leaving directory '/usr/local/lib/node_modules/log.io/node_modules/contextify/build'

> ws@0.4.32 install /usr/local/lib/node_modules/log.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/local/lib/node_modules/log.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:96: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/usr/local/lib/node_modules/log.io/node_modules/ws/build'

> log.io@0.3.4 postinstall /usr/local/lib/node_modules/log.io
> cake ensure:configuration

Creating ~/.log.io/ for configuration files.
If this fails, run npm using a specific user: npm install -g log.io --user 'ubuntu'
fs.js:922
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/root/.log.io/'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.action (/usr/local/lib/node_modules/log.io/Cakefile:79:10)
    at helpers.extend.invoke (/usr/local/lib/node_modules/log.io/node_modules/coffee-script/lib/coffee-script/cake.js:44:26)
    at Object.exports.run (/usr/local/lib/node_modules/log.io/node_modules/coffee-script/lib/coffee-script/cake.js:69:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/log.io/node_modules/coffee-script/bin/cake:7:38)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "log.io" "--user" "logio"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! log.io@0.3.4 postinstall: `cake ensure:configuration`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the log.io@0.3.4 postinstall script 'cake ensure:configuration'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the log.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cake ensure:configuration
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs log.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls log.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

Need help :( 

here is the [npm-debug.log](https://www.dropbox.com/s/nu9hwcpo1f6ynui/npm-debug.log?dl=1)

**Comment by tylercd100** [comment]
Have you tried running the command while being logged in as 'logio'?

**Comment by tylercd100** [comment]
also, does 'logio' have a home directory?

**Comment by Jonn3y** [comment]
> does 'logio' have a home directory?

sure, it has

> Have you tried running the command while being logged in as 'logio'?

yes, same problem. 

i tried `/usr/local/bin/npm install -g log.io --user "root"`
This was the only solution it worked. 

But Log.io isn't the perfect solution to me yet. Additionally I need a whole-file-view

**Comment by msmathers** [comment]
v0.4.3 uses node.js 12+ and doesn't require root/sudo access, so hopefully that should solve this issue.
