### ISSUE TITLE
Error while installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by donny08** [NarrativeScience/log.io#189]
Hello,
Node: v7.6.0
Npm: 4.1.2
I am trying to install logio : sudo npm install -g log.io --user "root" and getting below error:

```
devusr@devusr:~$ sudo npm install -g log.io --user "root"
npm WARN deprecated jquery@1.8.3: Versions of the jquery npm package older than 1.9.0 are patched versions that don't work in web browsers. Please upgrade to >=1.11.0.
/usr/bin/log.io-server -> /usr/lib/node_modules/log.io/bin/log.io-server
/usr/bin/log.io-harvester -> /usr/lib/node_modules/log.io/bin/log.io-harvester

> contextify@0.1.15 install /usr/lib/node_modules/log.io/node_modules/contextify
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/log.io/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function ‘static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)’:
../src/contextify.cc:131:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
In file included from /home/devusr/.node-gyp/7.6.0/include/node/v8.h:26:0,
                 from /home/devusr/.node-gyp/7.6.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/devusr/.node-gyp/7.6.0/include/node/v8.h:3662:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/home/devusr/.node-gyp/7.6.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:150:16: error: ‘class v8::ObjectTemplate’ has no member named ‘SetAccessCheckCallbacks’
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)’:
../src/contextify.cc:182:80: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
In file included from /home/devusr/.node-gyp/7.6.0/include/node/v8.h:26:0,
                 from /home/devusr/.node-gyp/7.6.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/devusr/.node-gyp/7.6.0/include/node/v8.h:3234:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/devusr/.node-gyp/7.6.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc: In static member function ‘static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)’:
../src/contextify.cc:209:67: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
In file included from /home/devusr/.node-gyp/7.6.0/include/node/v8.h:26:0,
                 from /home/devusr/.node-gyp/7.6.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/devusr/.node-gyp/7.6.0/include/node/v8.h:3234:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/devusr/.node-gyp/7.6.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/contextify.cc:210:71: warning: ‘v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
In file included from /home/devusr/.node-gyp/7.6.0/include/node/v8.h:26:0,
                 from /home/devusr/.node-gyp/7.6.0/include/node/node.h:42,
                 from ../src/contextify.cc:1:
/home/devusr/.node-gyp/7.6.0/include/node/v8.h:3234:30: note: declared here
                 Local<Value> GetRealNamedProperty(Local<String> key));
                              ^
/home/devusr/.node-gyp/7.6.0/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
contextify.target.mk:94: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/usr/lib/node_modules/log.io/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.0-41-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/log.io/node_modules/contextify
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
/usr/lib
`-- (empty)

npm ERR! Linux 4.8.0-41-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "log.io" "--user" "root"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/devusr/npm-debug.log
```

**Comment by danucalovj** [comment]
I'm getting the exact same error on 16.04. Tried installing v0.6.11 of node.js but required too many workarounds. Project doesn't seem to be supported/updated anymore. Shame, seems like a great tool.

**Comment by Conaclos** [comment]
Same here with:

- node 7.7.3
- npm 4.5.0

**Comment by tiemei** [comment]
+1 
- node v8.0.0 
- npm 5.0.0 
- Ubuntu 14.04.5 LTS

**Comment by tguless** [comment]
+1 
node v8.0.0
npm 4.2.0
MacOS 16.6.0 Darwin Kernel Version 16.6.0

**Comment by sjtilston** [comment]
Same here, on a DO droplet

**Comment by fishman1986** [comment]
Successfully installed with "sudo npm install -g log.io --user 'root'", I don't know what happened exactly, but it works. 
--- 
16.04.3
node, 6.11.0

**Comment by chenglongzjg** [comment]
same here
os: centos 7 86_64
node: v8.9.4
npm: 5.6.0

but it works when i run '**sudo su -**' first.

**Comment by nurettin** [comment]
--user 'root' works when I install nodejs-legacy

**Comment by msmathers** [comment]
v0.4.3 uses node.js 12+, and doesn't require any sudo/root access.
