### ISSUE TITLE
 log.io-server Running for a period of time, automatically throwing exceptions

### ISSUE THREAD

**Issue by timosir** [NarrativeScience/log.io#203]
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by timosir** [comment]
[root@localhost nodejs]# npm -v
6.5.0-next.0
[root@localhost nodejs]#  node -v
v11.6.0

**Comment by msmathers** [comment]
Looks like one or more harvester processes are resetting their connections to the server.  Both the harvester and server have been rewritten in v0.4.3, give those a try and report back if the same issue occurs.
