### ISSUE TITLE
log.io-file-input   dead start

### ISSUE THREAD

**Issue by fency12** [NarrativeScience/log.io#238]
[root@tools01 .log.io]# log.io-file-input
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:523:3)
    at tryReadSync (fs.js:348:20)
    at Object.readFileSync (fs.js:385:19)
    at loadConfig (/usr/local/lib/node_modules/log.io-file-input/lib/index.js:28:42)
    at _callee$ (/usr/local/lib/node_modules/log.io-file-input/lib/index.js:48:20)
    at tryCatch (/usr/local/lib/node_modules/log.io-file-input/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/log.io-file-input/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/log.io-file-input/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/usr/local/lib/node_modules/log.io-file-input/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/usr/local/lib/node_modules/log.io-file-input/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}

**Comment by msmathers** [comment]
Can you copy and paste the contents of `~/.log.io/inputs/file.json` here?

**Comment by fency12** [comment]
~/.log.io/inputs/file.json   This configuration is correct;
Later, I deleted the ~/log.io directory and the configuration in /usr/local/lib/node_modules/log.io-file-input/config.json can be started normally;
So far, that's how it works.
thank you

**Comment by fency12** [comment]
> Can you copy and paste the contents of `~/.log.io/inputs/file.json` here?

~/.log.io/inputs/file.json This configuration is correct;
Later, I deleted the ~/log.io directory and the configuration in /usr/local/lib/node_modules/log.io-file-input/config.json can be started normally;
So far, that's how it works.
thank you

**Comment by fency12** [comment]
~/.log.io/inputs/file.json 文件是默认的文件，没有自己修改过，确保是正确的；但一直无法启动；
后来删除~/.log.io/文件夹使用模块内的配置文件/usr/local/lib/node_modules/log.io-file-input/config.json 启动成功，目前是这么处理的。

**Comment by msmathers** [comment]
The `config.js` provided with the NPM package contains sample file paths that likely won't work on most machines... I'll make a ticket to remove these and have the file input throw an error if it can't find valid configuration.

**Comment by fency12** [comment]
thank you , I hope the better.

**Comment by fency12** [comment]
> The `config.js` provided with the NPM package contains sample file paths that likely won't work on most machines... I'll make a ticket to remove these and have the file input throw an error if it can't find valid configuration.

thank you , I hope the better.
