### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 444

### ISSUE THREAD

**Issue by johnbritto1** [NarrativeScience/log.io#245]
Log.io version: v0.4.16
nodejs v12.18.2
npm v6.14.5

root@mint:~# log.io-file-input
SyntaxError: Unexpected token } in JSON at position 444
    at JSON.parse (<anonymous>)
    at loadConfig (/usr/lib/node_modules/log.io-file-input/lib/index.js:33:21)
    at _callee$ (/usr/lib/node_modules/log.io-file-input/lib/index.js:53:20)
    at tryCatch (/usr/lib/node_modules/log.io-file-input/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/log.io-file-input/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/usr/lib/node_modules/log.io-file-input/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/usr/lib/node_modules/log.io-file-input/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/usr/lib/node_modules/log.io-file-input/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /usr/lib/node_modules/log.io-file-input/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)

**Comment by msmathers** [comment]
You likely have a config file with invalid JSON... Try running your `file-input.json` through a JSON validator.

**Comment by johnbritto1** [comment]
I copied your sample configuration file and try to validate on jsonlint.com, here is the result.

Error: Parse error on line 20:
...			"depth": 99,				}			}		}	]}
----------------------^
Expecting 'STRING', got '}'

 There is a typo mistake in your sample configurations file. 
"depth": 99,    (The extra comma after 99)

Appreciate your work.
Thank you.
