### ISSUE TITLE
Having issues on Centos 7

### ISSUE THREAD

**Issue by tomboxmeme** [NarrativeScience/log.io#257]
Wondering if you've seen this before, struggling to try to track it down.

When trying to launch the file input
```
SyntaxError: Unexpected token } in JSON at position 444
    at JSON.parse (<anonymous>)
    at loadConfig (/usr/lib/node_modules/log.io-file-input/lib/index.js:33:21)
    at _callee$ (/usr/lib/node_modules/log.io-file-input/lib/index.js:53:20)
    at tryCatch (/usr/lib/node_modules/log.io-file-input/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/log.io-file-input/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/usr/lib/node_modules/log.io-file-input/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/usr/lib/node_modules/log.io-file-input/node_modules/@babel/runtime/helpers/asyncToGenerator/index.js:3:24)
    at _next (/usr/lib/node_modules/log.io-file-input/node_modules/@babel/runtime/helpers/asyncToGenerator/index.js:25:9)
    at /usr/lib/node_modules/log.io-file-input/node_modules/@babel/runtime/helpers/asyncToGenerator/index.js:32:7
    at new Promise (<anonymous>)
```

**Comment by aizhimou** [comment]
I also ran into the same problem, and later found out that my configuration file was written incorrectly, maybe you can check your configuration file
