### ISSUE TITLE
Clarify "fs.js:1051" error caused by incorrect log permissions

### ISSUE THREAD

**Issue by holachek** [NarrativeScience/log.io#86]
I get this error when I specify a log file to watch that can't be read due to restricted access permissions (e.g., a log file mode of 400):

```
fs.js:1051
    throw errnoException(process._errno, 'watch');
          ^
Error: watch EACCES
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at LogStream._watchFile (/usr/lib/node_modules/log.io/lib/harvester.js:83:27)
    at LogStream.watch (/usr/lib/node_modules/log.io/lib/harvester.js:66:14)
   ....
```

It took me a while to figure out that file permissions were the problem. I think it would be helpful to clarify that the error is due to file permissions.... maybe echo out an error message like "Can't read log file due to incorrect permissions." so future users don't have to troubleshoot for a solution.

**Comment by seanmavley** [comment]
@holachek And so what was the solution?
